apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: spring-apiserver
resources:
- pgdb.yaml
- service.yaml
- cm.yaml
# - instrumentation.yaml
- deployment.yaml
- servicemonitor.yaml