apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-apiserver
spec:
  endpoints:
  - interval: 30s
    port: 9090-tcp
    scheme: http
    path: "/actuator/prometheus"
  selector:
    matchLabels:
      app.kubernetes.io/component: spring-apiserver