---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-apiserver
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: spring-apiserver
spec:
  destination:
    namespace: spring-apiserver
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/openshift
    repoURL: https://github.com/joshgav/spring-apiserver.git
    targetRevision: main
    kustomize: {}
  syncPolicy:
    automated: {}
