# see https://pipelinesascode.com/docs/guide/authoringprs/
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spring-apiserver-pr-pipeline
  namespace: spring-apiserver
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main,tekton]"
    pipelinesascode.tekton.dev/on-event: "pull_request"
    pipelinesascode.tekton.dev/task: "[git-clone,buildah]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  labels:
    tekton.dev/pipeline: spring-boot-build-pipeline
    type: pipeline
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: spring-boot-build-pipeline
  params:
    - name: source-repo
      value: {{repo_url}}
    - name: source-branch
      value: {{source_branch}}
    - name: output-image
      value: registry-quay-quay.apps.ipi.aws.joshgav.com/joshgav/spring-apiserver:pr-{{pull_request_number}}
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi