# see https://pipelinesascode.com/docs/guide/authoringprs/
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spring-apiserver-push-pipeline
  namespace: spring-apiserver
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/on-event: "push"
    pipelinesascode.tekton.dev/task: "[git-clone,buildah]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  labels:
    app: spring-apiserver
spec:
  serviceAccountName: pipeline
  params:
  - name: source-repo
    value: 'https://github.com/joshgav/spring-apiserver.git'
  - name: source-branch
    value: main
  - name: output-image
    value: registry-quay-quay.apps.ipi.aws.joshgav.com/joshgav/spring-apiserver:latest
  workspaces:
  - name: source-folder
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    params:
    - name: source-repo
      description: source repo that contains the application code
      type: string
    - name: source-branch
      description: source branch to build from
      type: string
    - name: output-image
      description: reference of the image that will get created
      type: string
    tasks:
    - name: git-clone
      params:
      - name: url
        value: $(params.source-repo)
      - name: revision
        value: $(params.source-branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: source-folder
    - name: buildah
      params:
      - name: IMAGE
        value: $(params.output-image)
      runAfter:
      - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
      - name: source
        workspace: source-folder
    workspaces:
    - name: source-folder