# see https://pipelinesascode.com/docs/guide/authoringprs/
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spring-apiserver-default-pipeline
  namespace: spring-apiserver
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/on-event: "push"
    pipelinesascode.tekton.dev/task: "[git-clone,buildah]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  labels:
    tekton.dev/pipeline: spring-boot-build-pipeline
    type: pipeline
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: spring-boot-build-pipeline
  params:
    - name: source-repo
      value: 'https://github.com/joshgav/spring-apiserver.git'
    - name: source-branch
      value: main
    - name: output-image
      value: registry-quay-quay.apps.ipi.aws.joshgav.com/joshgav/spring-apiserver:latest
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi